name: Deploy Spring Boot app to Railway

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17' # ou 21 selon ta version

      - name: Build the application
        run: ./mvnw clean package -DskipTests

      - name: Deploy to Railway
        uses: railwayapp/cli-action@v1
        with:
          railwayToken: ${{ secrets.RAILWAY_TOKEN }}
